name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Multi Checkout
        uses: ./
        with:
          repositories: |
            vweevers/hallmark-lint-action
            vweevers/additional-tags-action@v1.0
      - name: Verify
        run: git -C ../vweevers/additional-tags-action log -n 1
      - name: Test
        run: npm it
